;Programa que limpia pantalla y escribe una cadena en el renglón12, columna 30.
DATOS SEGMENT PARA 'DATA'
  CADENA  DB      'ESTO ES UNA PRUEBA$'
  REN     DB      12
  COL     DB      30
  RP0      DW      150
  CP0      DW      100
  RP1      DW      200
  CP1      DW      200
  RP       DW     ?
  CP       DW     ?
  COLOR   DB      03
  FONDO   DB      07
  FRENTE  DB      00
DATOS ENDS

PILA SEGMENT PARA STACK 'STACK'
  DW      100     DUP(0)
PILA ENDS

CODIGO SEGMENT PARA 'CODE'
  ASSUME  CS:CODIGO, DS:DATOS, SS:PILA, ES:NOTHING

  MODO_GRAFICO PROC NEAR
     MOV AH,00
     MOV AL,12H
     INT 10H
     RET
  MODO_GRAFICO ENDP

  MODO_TEXTO PROC NEAR
     MOV AH,00
     MOV AL,03
     INT 10H
  MODO_TEXTO ENDP

  PINTA_PIXEL PROC NEAR
     MOV AH,0CH
     MOV AL,COLOR 
     MOV BH,0  ;PAGINA
     MOV CX,RP ; RENGLON
     MOV DX,CP ; COLUMNA
     INT 10H
     RET
  PINTA_PIXEL ENDP
  
  PINTA_LINEA_H PROC NEAR
 OTRO:
     CALL PINTA_PIXEL
     INC CP
     MOV AX,CP
     CMP AX,CP1
     JNLE FIN3
     JMP OTRO
  FIN3:
     RET
  PINTA_LINEA_H ENDP

  PINTA_LINEA_V PROC NEAR
  OTRO1:
     CALL PINTA_PIXEL
     INC RP
     MOV AX,RP
     CMP AX,RP1
     JG FIN4
     JMP OTRO1
 FIN4:
     RET
  PINTA_LINEA_V ENDP

  CUADRO PROC NEAR
     MOV DX,RP0
     MOV CX,CP0
     MOV RP,DX
     MOV CP,CX
     CALL PINTA_LINEA_H
     MOV DX,RP1
     MOV CX,CP0
     MOV RP,DX
     MOV CP,CX
     CALL PINTA_LINEA_H
     MOV DX,RP0
     MOV CX,CP0
     MOV RP,DX
     MOV CP,CX
     CALL PINTA_LINEA_V
     MOV DX,RP0
     MOV CX,CP1
     MOV RP,DX
     MOV CP,CX
     CALL PINTA_LINEA_V
     RET
  CUADRO ENDP

  POSICIONA_CURSOR PROC NEAR
     MOV AH,02
     MOV BH,00
     MOV DH,REN
     MOV DL,COL
     INT 10H
     RET
  POSICIONA_CURSOR ENDP

  LETRERO  PROC NEAR
     MOV AH,09
     LEA DX, CADENA
     INT 21H
     RET
  LETRERO ENDP

  DES_CADE_ATRI PROC NEAR
     MOV AH,13H
     MOV AL,01
     MOV BH,0
     MOV BL,42H
     LEA BP, CADENA
     MOV CX,18
     MOV DX,1010
     INT 10H
     RET
  DES_CADE_ATRI ENDP

  PRINCIPAL PROC FAR
     PUSH DS
     XOR AX, AX
     PUSH AX
     MOV AX, DATOS
     MOV DS, AX
     MOV ES, AX
     CALL MODO_GRAFICO
     CALL CUADRO
     CALL DES_CADE_ATRI
     MOV AH,10H
     INT 16H
     CALL POSICIONA_CURSOR
     CALL LETRERO
     MOV AH,10H
     INT 16H
     CALL MODO_TEXTO
     RET
  PRINCIPAL ENDP

CODIGO ENDS
  END PRINCIPAL